#!/usr/bin/env bash
# Script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script
# Install and configure HAProxy on my lb-01 server
sudo apt-get -y update
sudo apt-get -y install haproxy

# edit config file
server_config=\
"
frontend kevinm-frontend
	bind *:80
	mode http
	default_backend kevinm-backend
backend kevinm-backend
	balance roundrobin
	server 120033-web-01 52.86.112.73:80 check
	server 120033-web-02 100.26.225.71:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# Enable haproxy to started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
