#!/usr/bin/env bash
# debugging nginx port 80
# delete existing ../sites-enabled/default and replace it with
# ../sites-available/default. by creating a symbolic link
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
