#!/usr/bin/env bash
# A script that:
# Creates the file /var/run/myscript.pid containing its PID,
# Displays to infinity and beyond indefinitely,
# Displays I hate the kill command when receivinga SIGTERM signal,
# Displays 'Y U no love me?!' when receiving a SIGINT signal,
# Deletes the file /var/run/myscript.pid,
# Terminates itself whenreceiving a SIGQUIT or SIGTERM signal.

echo $$ >> /var/run/myscript.pid

trap "echo 'I hate the kill command'; rm -rf /var/run/myscript.pid; exit" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap "rm -rf /var/run/myscript.pid; exit" SIGQUIT

while true
do
	echo 'To infinity and beyond'
	sleep 2
done
