#!/usr/bin/env bash
# A script that parses Apache log files in list format
# Group visitors by IP and HTTP status code
# Displays the number of occurrences, IP, and HTTP status
# code of each log, in sorted order.

myfile="apache-access.log"
awk -F' ' '{ print $1, $9}' $myfile | sort | uniq -c|sort -nr
